server:
  # 端口号
  prot: 8201
  application:
    # 服务名称
    name: service-hosp

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 环境设置
  profiles:
    active: pro

# 以下配置是为了让MyBatis映射指定Mybatis的Mapper文件
mybatis_plus:
  mapper-locations: classpath:com/chen/medical/hosp/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl